import ex1 from "../pictures/hue/ex1.png";
import ex2 from "../pictures/hue/ex2.jpg";
import ex3 from "../pictures/hue/ex3.jpg";
import ex4 from "../pictures/hue/ex4.jpg";
import ex5 from "../pictures/hue/ex5.webp";
import ex6 from "../pictures/hue/ex6.jpg";
import ex7 from "../pictures/hue/ex7.webp";
import ex8 from "../pictures/hue/ex8.webp";
import ex9 from "../pictures/hue/ex9.avif";
import ex10 from "../pictures/hue/ex10.jpg";
import ex11 from "../pictures/hue/ex11.avif";
import ex12 from "../pictures/hue/ex12.jpg";
import ex13 from "../pictures/hue/ex13.jpg";
import ex14 from "../pictures/hue/ex14.webp";
import ex15 from "../pictures/hue/ex15.webp";
import ex16 from "../pictures/hue/ex16.png";
import ex17 from "../pictures/hue/ex17.webp";
import ex18 from "../pictures/hue/ex18.webp";
import ex19 from "../pictures/hue/ex19.gif";
import ex20 from "../pictures/hue/ex20.webp";
import ex21 from "../pictures/hue/ex21.webp";
import ex22 from "../pictures/hue/ex22.jpg";
import ex23 from "../pictures/hue/ex23.webp";
import ex24 from "../pictures/hue/ex24.avif";
import ex25 from "../pictures/hue/ex25.avif";
import ex26 from "../pictures/hue/ex26.jpeg";
import ex27 from "../pictures/hue/ex27.jpg";
import ex28 from "../pictures/hue/ex28.jpg";
import ex29 from "../pictures/hue/ex29.jpg";
import ex30 from "../pictures/hue/ex30.webp";
import ex31 from "../pictures/hue/ex31.jpg";
import ex32 from "../pictures/hue/ex32.webp";
import ex33 from "../pictures/hue/ex33.avif";
import ex34 from "../pictures/hue/ex34.jpeg";
import ex35 from "../pictures/hue/ex35.webp";
import ex36 from "../pictures/hue/ex36.jpg";
import ex37 from "../pictures/hue/ex37.jpg";
import ex38 from "../pictures/hue/ex38.webp";
import ex39 from "../pictures/hue/ex39.jpg";
import ex40 from "../pictures/hue/ex40.webp";
import ex41 from "../pictures/hue/ex41.jpg";
import ex42 from "../pictures/hue/ex42.avif";
import ex43 from "../pictures/hue/ex43.avif";
import ex44 from "../pictures/hue/ex44.jpg";
import ex45 from "../pictures/hue/ex45.jpg";
import ex46 from "../pictures/hue/ex46.webp";
import ex47 from "../pictures/hue/ex47.webp";
import ex48 from "../pictures/hue/ex48.jpg";
import ex49 from "../pictures/hue/ex49.jpg";
import ex50 from "../pictures/hue/ex50.jpg";
import ex51 from "../pictures/hue/ex51.jpg";
import ex52 from "../pictures/hue/ex52.webp";
import ex53 from "../pictures/hue/ex53.webp";
import ex54 from "../pictures/hue/ex54.jpg";
import ex55 from "../pictures/hue/ex55.jpg";
import ex56 from "../pictures/hue/ex56.webp";
import ex57 from "../pictures/hue/ex57.jpg";
import ex58 from "../pictures/hue/ex58.jpg";
import ex59 from "../pictures/hue/ex59.jpg";
import ex60 from "../pictures/hue/ex60.jpg";
import ex61 from "../pictures/hue/ex61.jpg";
import ex62 from "../pictures/hue/ex62.avif";
import ex63 from "../pictures/hue/ex63.webp";
import ex64 from "../pictures/hue/ex64.webp";
import ex65 from "../pictures/hue/ex65.webp";
import ex66 from "../pictures/hue/ex66.jpg";
import ex67 from "../pictures/hue/ex67.jpg";
import ex68 from "../pictures/hue/ex68.jpg";
import ex69 from "../pictures/hue/ex69.jpg";
import ex70 from "../pictures/hue/ex70.webp";
import ex71 from "../pictures/hue/ex71.avif";
import ex72 from "../pictures/hue/ex72.jpg";
import ex73 from "../pictures/hue/ex73.jpg";
import ex74 from "../pictures/hue/ex74.avif";
import ex75 from "../pictures/hue/ex75.jpg";
import ex76 from "../pictures/hue/ex76.webp";
import ex77 from "../pictures/hue/ex77.webp";
import ex78 from "../pictures/hue/ex78.jpg";
import ex79 from "../pictures/hue/ex79.avif";
import ex80 from "../pictures/hue/ex8.webp";
import ex81 from "../pictures/hue/ex81.webp";
import ex82 from "../pictures/hue/ex82.jpg";
import ex83 from "../pictures/hue/ex83.avif";
import ex84 from "../pictures/hue/ex84.jpg";
import ex85 from "../pictures/hue/ex85.webp";
import ex86 from "../pictures/hue/ex86.jpg";
import ex87 from "../pictures/hue/ex87.webp";
import ex88 from "../pictures/hue/ex88.jpg";
import ex89 from "../pictures/hue/ex89.webp";
import ex90 from "../pictures/hue/ex90.webp";
import ex91 from "../pictures/hue/ex91.webp";
import ex92 from "../pictures/hue/ex92.jpg";
import ex93 from "../pictures/hue/ex93.jpg";
import pd12 from "../pictures/hue/pd12.avif";
import pd13 from "../pictures/hue/pd13.jpg";
import pd37 from "../pictures/hue/pd37.jpg";
import pd35 from "../pictures/hue/pd35.avif";
import pd36 from "../pictures/hue/pd36.avif";
import ex94 from "../pictures/hue/ex94.jpg";
import ex95 from "../pictures/hue/ex95.jpg";
import ex96 from "../pictures/hue/ex96.jpg";
import ex97 from "../pictures/hue/ex97.webp";
import ex98 from "../pictures/hue/ex98.webp";
import ex99 from "../pictures/hue/ex99.jpg";
import ex100 from "../pictures/hue/ex100.webp";
import ex101 from "../pictures/hue/ex101.jpg";
import ex102 from "../pictures/hue/ex102.webp";
import ex103 from "../pictures/hue/ex103.jpg";
import ex104 from "../pictures/hue/ex104.jpg";
import ex105 from "../pictures/hue/ex105.webp";
import ex106 from "../pictures/hue/ex106.webp";
import ex107 from "../pictures/hue/ex107.jpg";
import ex108 from "../pictures/hue/ex108.jpg";
import ex109 from "../pictures/hue/ex109.jpg";

// products.js
export const allProducts = [
  // Men's Belts (1-4)
  {
    id: 1,
    name: "Classic Leather Belt",
    price: 49.99,
    originalPrice: 59.99,
    category: "Men",
    subcategory: "Accessories",
    type: "Belts",
    collection: "Minimalism and fantasy",
    image: ex1,
    additionalImages: [ex94, ex95],
    inStock: true,
    colors: ["Black", "Brown", "Tan"],
    sizes: ['S (30-32")', 'M (34-36")', 'L (38-40")'],
    description:
      "Full-grain leather belt with polished buckle, perfect for both casual and formal occasions.",
    details: [
      '1.5" width',
      "Brushed stainless steel buckle",
      "7 adjustment holes",
      "Hand-stitched edges",
    ],
    materials: "100% Italian leather, Stainless steel",
    care: "Wipe clean, condition monthly",
    rating: 4.7,
    reviewCount: 128,
    isBestSeller: true,
  },
  {
    id: 2,
    name: "Reversible Dress Belt",
    price: 59.99,
    category: "Men",
    subcategory: "Accessories",
    type: "Belts",
    collection: "Winter 23",
    image: ex2,
    additionalImages: [ex96],
    inStock: true,
    colors: ["Black/Brown", "Tan/Black"],
    sizes: ["S", "M", "L", "XL"],
    description:
      "Versatile reversible belt with dual-color leather and quick-release buckle.",
    details: [
      "Reversible design",
      "Quick-release buckle",
      '1.25" width',
      "Matte finish",
    ],
    materials: "Genuine leather, Zinc alloy buckle",
    care: "Avoid moisture, store flat",
    rating: 4.5,
    reviewCount: 87,
  },
  {
    id: 3,
    name: "Reversible Italian Leather Belt",
    price: 89.99,
    category: "Men",
    subcategory: "Accessories",
    type: "Belts",
    collection: "Winter 23",
    image: ex94,
    additionalImages: [ex2, ex95],
    inStock: true,
    colors: ["Black/Brown", "Tan/Black"],
    sizes: ["S", "M", "L", "XL"],
    description:
      "Premium Italian leather belt with smooth reversible design and brushed metal buckle.",
    details: [
      "Butter-soft leather",
      "Scratch-resistant buckle",
      "Lifetime guarantee",
      "Unisex sizing",
    ],
    materials: "Italian calf leather, Stainless steel",
    care: "Use leather conditioner",
    rating: 4.8,
    reviewCount: 64,
    isNew: true,
  },
  {
    id: 4,
    name: "Braided Leather Belt",
    price: 59.99,
    category: "Men",
    subcategory: "Accessories",
    type: "Belts",
    collection: "Summer 24",
    image: ex95,
    additionalImages: [ex1, ex94],
    inStock: true,
    colors: ["Brown", "Navy"],
    sizes: ["S", "M", "L"],
    description: "Handwoven braided leather belt with elastic comfort stretch.",
    details: [
      "Flexible braided design",
      "No-hole adjustment",
      '1" width',
      "Casual style",
    ],
    materials: "Woven leather, Elastic core",
    care: "Spot clean only",
    rating: 4.3,
    reviewCount: 42,
  },

  // Men's Gifts (5-10)
  {
    id: 5,
    name: "Leather Wallet Set",
    price: 79.99,
    category: "Men",
    subcategory: "Accessories",
    type: "Gifts for him",
    collection: "Ready to wear",
    image: ex5,
    additionalImages: [ex106, ex107],
    inStock: true,
    colors: ["Black", "Brown", "Cognac"],
    description: "Premium leather bifold wallet with matching card holder.",
    details: [
      "12 card slots",
      "ID window",
      "2 bill compartments",
      "Includes RFID protection",
    ],
    materials: "Full-grain leather, Polyester lining",
    care: "Wipe with damp cloth",
    rating: 4.6,
    reviewCount: 156,
    isBestSeller: true,
  },
  {
    id: 6,
    name: "Personalized Cufflinks Set",
    price: 149.99,
    category: "Men",
    subcategory: "Accessories",
    type: "Gifts for him",
    collection: "Ready to wear",
    image: ex96,
    additionalImages: [ex5],
    inStock: true,
    colors: ["Silver", "Gold", "Gunmetal"],
    description: "Elegant cufflinks with optional monogram engraving.",
    details: [
      "Solid metal construction",
      "Secure toggle closure",
      "Free engraving",
      "Gift box included",
    ],
    materials: "925 Sterling silver, 18k gold plating",
    care: "Polish with jewelry cloth",
    rating: 4.9,
    reviewCount: 203,
  },
  {
    id: 7,
    name: "Premium Whiskey Decanter Set",
    price: 199.99,
    category: "Men",
    subcategory: "Accessories",
    type: "Gifts for him",
    collection: "Ready to wear",
    image: ex7,
    additionalImages: [ex97],
    inStock: true,
    description: "Hand-cut crystal decanter with two whiskey glasses.",
    details: [
      "Lead-free crystal",
      "900ml capacity",
      "Airtight stopper",
      "Laser-etched design",
    ],
    materials: "Crystal glass, Cork stopper",
    care: "Hand wash only",
    rating: 5.0,
    reviewCount: 89,
    isBestSeller: true,
  },
  {
    id: 8,
    name: "Leather Travel Wallet",
    price: 129.99,
    category: "Men",
    subcategory: "Accessories",
    type: "Gifts for him",
    collection: "Ready to wear",
    image: ex97,
    additionalImages: [ex5, ex106],
    inStock: true,
    colors: ["Black", "Brown"],
    description:
      "Passport holder with multiple card slots and boarding pass pocket.",
    details: [
      "Fits passport and tickets",
      "6 card slots",
      "Pen holder",
      "Zippered coin pocket",
    ],
    materials: "Vegetable-tanned leather, Brass zipper",
    care: "Condition leather quarterly",
    rating: 4.7,
    reviewCount: 112,
  },
  {
    id: 9,
    name: "Classic Card Holder",
    price: 59.99,
    category: "Men",
    subcategory: "Accessories",
    type: "Gifts for him",
    collection: "Ready to wear",
    image: ex106,
    additionalImages: [ex5],
    inStock: true,
    colors: ["Black", "Tan", "Navy"],
    description: "Slim leather card case for essential cards and cash.",
    details: [
      "Holds 4-6 cards",
      "Central cash slot",
      "RFID blocking",
      '3.5" x 2.25"',
    ],
    materials: "Top-grain leather, Polyester lining",
    care: "Wipe clean",
    rating: 4.5,
    reviewCount: 231,
  },
  {
    id: 10,
    name: "Slim RFID Wallet",
    price: 89.99,
    category: "Men",
    subcategory: "Accessories",
    type: "Gifts for him",
    collection: "Ready to wear",
    image: ex107,
    additionalImages: [ex5, ex106],
    inStock: true,
    colors: ["Black", "Brown", "Gray"],
    description: "Minimalist wallet with advanced RFID protection technology.",
    details: [
      "Blocks 13.56MHz signals",
      "Holds 8 cards",
      "Money clip",
      '0.3" thin',
    ],
    materials: "Nylon fabric, Aluminum plate",
    care: "Wipe clean",
    rating: 4.8,
    reviewCount: 178,
    isNew: true,
  },

  // Men's Jewelry (11-16)
  {
    id: 11,
    name: "Silver Cufflinks",
    price: 89.99,
    category: "Men",
    subcategory: "Accessories",
    type: "Jewelry",
    collection: "Pre Fall 23",
    image: ex6,
    additionalImages: [ex98, ex99],
    inStock: true,
    colors: ["Polished", "Brushed"],
    description: "Classic round cufflinks with secure double-toggle closure.",
    details: [
      "18mm diameter",
      "925 sterling silver",
      "Gift box included",
      "Weight: 8g",
    ],
    materials: "Sterling silver, Rhodium plating",
    care: "Polish with silver cloth",
    rating: 4.6,
    reviewCount: 94,
  },
  {
    id: 12,
    name: "Titanium Signet Ring",
    price: 179.99,
    category: "Men",
    subcategory: "Accessories",
    type: "Jewelry",
    collection: "Pre Fall 23",
    image: ex98,
    additionalImages: [ex6],
    inStock: true,
    sizes: ["8", "9", "10", "11", "12"],
    description: "Modern signet ring crafted from lightweight titanium.",
    details: [
      "8mm flat face",
      "Hypoallergenic",
      "Laser engraving available",
      "Weight: 4g",
    ],
    materials: "Grade 2 titanium",
    care: "Wipe with microfiber cloth",
    rating: 4.7,
    reviewCount: 56,
  },
  {
    id: 13,
    name: "Black Onyx Bracelet",
    price: 129.99,
    category: "Men",
    subcategory: "Accessories",
    type: "Jewelry",
    collection: "Pre Fall 23",
    image: ex99,
    additionalImages: [ex100],
    inStock: true,
    sizes: ['7"', '8"', '9"'],
    description: "Beaded bracelet featuring genuine black onyx stones.",
    details: [
      "8mm beads",
      "Adjustable leather tie",
      "Sterling silver accents",
      "Hand-knotted",
    ],
    materials: "Black onyx, Leather cord, Sterling silver",
    care: "Avoid water contact",
    rating: 4.8,
    reviewCount: 72,
    isNew: true,
  },
  {
    id: 14,
    name: "Minimalist Silver Chain",
    price: 89.99,
    category: "Men",
    subcategory: "Accessories",
    type: "Jewelry",
    collection: "Minimalism and fantasy",
    image: ex100,
    additionalImages: [ex6, ex99],
    inStock: true,
    sizes: ['18"', '20"', '22"'],
    description: "Delicate silver chain with lobster clasp closure.",
    details: [
      "1.5mm width",
      "925 sterling silver",
      "Secure clasp",
      "Hypoallergenic",
    ],
    materials: "Sterling silver",
    care: "Store in anti-tarnish bag",
    rating: 4.5,
    reviewCount: 118,
  },
  {
    id: 15,
    name: "Gold-Tone Tie Clip",
    price: 69.99,
    category: "Men",
    subcategory: "Accessories",
    type: "Jewelry",
    collection: "Pre Fall 23",
    image: ex108,
    additionalImages: [ex6],
    inStock: true,
    description: "Sleek tie clip with secure spring mechanism.",
    details: [
      '2.5" length',
      "Anti-slip design",
      "18k gold plating",
      "Weight: 12g",
    ],
    materials: "Brass base, 18k gold plating",
    care: "Polish with soft cloth",
    rating: 4.4,
    reviewCount: 63,
  },
  {
    id: 16,
    name: "Matte Black Ring",
    price: 99.99,
    category: "Men",
    subcategory: "Accessories",
    type: "Jewelry",
    collection: "Pre Fall 23",
    image: ex109,
    additionalImages: [ex98],
    inStock: true,
    sizes: ["8", "9", "10", "11", "12"],
    description: "Bold matte black band ring with subtle texture.",
    details: ["8mm width", "Lightweight", "Hypoallergenic", "Unisex design"],
    materials: "Tungsten carbide",
    care: "Wipe clean",
    rating: 4.6,
    reviewCount: 87,
  },

  // Men's Accessories - Pocket squares
  {
    id: 17,
    name: "Silk Pocket Square",
    price: 29.99,
    category: "Men",
    subcategory: "Accessories",
    type: "Pocket Squares",
    collection: "Pre Fall 23",
    image: ex3,
    additionalImages: [ex4, ex10],
    inStock: true,
    colors: ["Navy", "Burgundy", "Emerald Green"],
    description:
      "Luxury silk pocket square with hand-rolled edges for formal occasions.",
    details: [
      "100% pure mulberry silk",
      '12" x 12" perfect size',
      "Hand-rolled edges for durability",
      "Subtle tonal pattern",
    ],
    materials: "100% Silk",
    care: "Dry clean only",
    rating: 4.6,
    reviewCount: 38,
  },

  // Men's Accessories - Ties
  {
    id: 18,
    name: "Silk Necktie",
    price: 59.99,
    category: "Men",
    subcategory: "Accessories",
    type: "Ties",
    collection: "Winter 23",
    image: ex4,
    additionalImages: [ex7, ex8],
    inStock: true,
    colors: ["Navy", "Burgundy", "Charcoal"],
    sizes: ['Standard (58")', 'Extra Long (62")'],
    description:
      "Premium silk tie with classic diagonal stripe pattern for business or formal wear.",
    details: [
      "100% silk twill fabric",
      '3.25" width - modern classic',
      "Unlined construction for perfect knot",
      "Self-tip finishing",
    ],
    materials: "100% Silk",
    care: "Dry clean only",
    rating: 4.7,
    reviewCount: 92,
    isBestSeller: true,
  },
  {
    id: 19,
    name: "Geometric Print Skinny Tie",
    price: 79.99,
    category: "Men",
    subcategory: "Accessories",
    type: "Ties",
    collection: "Winter 23",
    image: ex101,
    additionalImages: [ex7, ex8],
    inStock: true,
    colors: ["Black/White", "Navy/Gold", "Burgundy"],
    sizes: ['Skinny (2.5")'],
    description:
      "Contemporary skinny tie with bold geometric patterns for modern style.",
    details: [
      '2.5" ultra-slim width',
      "Modern geometric print",
      "Italian silk construction",
      "Adjustable keeper loop",
    ],
    materials: "100% Silk",
    care: "Dry clean only",
    rating: 4.5,
    reviewCount: 64,
    isNew: true,
  },
  {
    id: 20,
    name: "Patterned Tie",
    price: 49.99,
    category: "Men",
    subcategory: "Accessories",
    type: "Ties",
    collection: "Winter 23",
    image: ex7,
    additionalImages: [ex4, ex8],
    inStock: true,
    colors: ["Blue Paisley", "Red Floral", "Green Geometric"],
    sizes: ['Standard (57")'],
    description:
      "Versatile patterned tie perfect for adding personality to any outfit.",
    details: [
      '3" universal width',
      "All-season silk blend",
      "Reinforced tip",
      "Classic slip stitch construction",
    ],
    materials: "90% Silk, 10% Cotton",
    care: "Dry clean recommended",
    rating: 4.3,
    reviewCount: 47,
  },
  {
    id: 21,
    name: "Skinny Tie",
    price: 39.99,
    category: "Men",
    subcategory: "Accessories",
    type: "Ties",
    collection: "Winter 23",
    image: ex8,
    additionalImages: [ex4, ex7],
    inStock: true,
    colors: ["Black", "Navy", "Gray"],
    sizes: ['Skinny (2.25")'],
    description:
      "Essential solid-color skinny tie for modern professional looks.",
    details: [
      'Ultra-slim 2.25" width',
      "Matte finish fabric",
      "Interlining for structure",
      "Perfect for younger professionals",
    ],
    materials: "100% Polyester",
    care: "Hand wash cold, hang dry",
    rating: 4.4,
    reviewCount: 85,
  },
  {
    id: 22,
    name: "Business Tie Set",
    price: 99.99,
    category: "Men",
    subcategory: "Accessories",
    type: "Ties",
    collection: "Winter 23",
    image: ex9,
    additionalImages: [ex4, ex7, ex8],
    inStock: true,
    colors: ["Classic Set", "Modern Set", "Executive Set"],
    description:
      "Curated set of three premium ties for complete business wardrobe coverage.",
    details: [
      "Includes 3 coordinating ties",
      "Mix of solids and subtle patterns",
      '57" standard length',
      '3" universal width',
    ],
    materials: "100% Silk",
    care: "Dry clean only",
    rating: 4.8,
    reviewCount: 127,
    isBestSeller: true,
  },

  // Men's Accessories - Bow Ties
  {
    id: 23,
    name: "Classic Bow Tie",
    price: 49.99,
    category: "Men",
    subcategory: "Accessories",
    type: "Bow Ties",
    collection: "Winter 23",
    image: ex10,
    additionalImages: [ex11, ex23],
    inStock: true,
    colors: ["Black", "Navy", "Burgundy"],
    sizes: ["One Size"],
    description:
      "Self-tie bow tie for formal occasions, offering perfect butterfly shape.",
    details: [
      "100% satin silk",
      "Adjustable neck strap",
      "Classic butterfly shape",
      "Includes tying instructions",
    ],
    materials: "100% Silk",
    care: "Dry clean only",
    rating: 4.5,
    reviewCount: 56,
  },
  {
    id: 24,
    name: "Pre-tied Bow Tie",
    price: 39.99,
    category: "Men",
    subcategory: "Accessories",
    type: "Bow Ties",
    collection: "Winter 23",
    image: ex11,
    additionalImages: [ex10, ex23],
    inStock: true,
    colors: ["Black", "White", "Red"],
    sizes: ["One Size"],
    description:
      "Easy-wear pre-tied bow tie with adjustable band for perfect fit every time.",
    details: [
      "Pre-tied for convenience",
      "Adjustable neck strap",
      "Batwing shape",
      "Perfect for frequent wear",
    ],
    materials: "Polyester satin",
    care: "Spot clean only",
    rating: 4.2,
    reviewCount: 43,
  },

  // Men's Clothing - Suits
  {
    id: 25,
    name: "Slim Fit Suit",
    price: 349.99,
    originalPrice: 399.99,
    category: "Men",
    subcategory: "Clothing",
    type: "Suits",
    collection: "Winter 23",
    image: ex12,
    additionalImages: [pd12, ex13, pd13],
    inStock: true,
    colors: ["Navy", "Charcoal", "Black"],
    sizes: ["38R", "40R", "42R", "44R", "38L", "40L", "42L"],
    description:
      "Modern slim-fit suit with premium wool fabric that drapes elegantly for business or formal occasions.",
    details: [
      "Super 120s wool fabric",
      "Half-canvas construction",
      "Notch lapel jacket",
      "Flat front trousers",
      "Functional sleeve buttons",
    ],
    materials: "92% Wool, 7% Polyester, 1% Elastane",
    care: "Dry clean only, steam to remove wrinkles",
    rating: 4.8,
    reviewCount: 134,
    isBestSeller: true,
  },
  {
    id: 26,
    name: "Business Suit",
    price: 299.99,
    category: "Men",
    subcategory: "Clothing",
    type: "Suits",
    collection: "Winter 23",
    image: pd12,
    additionalImages: [ex12, ex13],
    inStock: true,
    colors: ["Navy Pinstripe", "Gray", "Black"],
    sizes: ["38R", "40R", "42R", "44R", "46R", "38L", "40L", "42L"],
    description:
      "Classic business suit with timeless cut and comfortable stretch fabric for all-day wear.",
    details: [
      "Regular fit jacket",
      "Pleated trousers",
      "Durable wool blend",
      "Includes matching vest option",
      "Multiple interior pockets",
    ],
    materials: "75% Wool, 23% Polyester, 2% Spandex",
    care: "Dry clean only, store on wooden hanger",
    rating: 4.6,
    reviewCount: 98,
  },
  {
    id: 27,
    name: "Tweed Suit",
    price: 449.99,
    category: "Men",
    subcategory: "Clothing",
    type: "Suits",
    collection: "Winter 23",
    image: ex13,
    additionalImages: [pd12, pd13],
    inStock: true,
    colors: ["Brown Herringbone", "Gray Check", "Navy Pattern"],
    sizes: ["38R", "40R", "42R", "44R", "38L", "40L"],
    description:
      "Premium tweed suit with textured fabric perfect for winter weddings and formal events.",
    details: [
      "100% wool tweed",
      "Full canvas construction",
      "Three-button jacket",
      "High-rise trousers",
      "Functional cuff buttons",
    ],
    materials: "100% Wool",
    care: "Professional dry clean only",
    rating: 4.9,
    reviewCount: 67,
    isNew: true,
  },
  {
    id: 28,
    name: "Three-piece Suit",
    price: 499.99,
    category: "Men",
    subcategory: "Clothing",
    type: "Suits",
    collection: "Winter 23",
    image: pd13,
    additionalImages: [ex12, ex13],
    inStock: true,
    colors: ["Navy", "Charcoal", "Midnight"],
    sizes: ["38R", "40R", "42R", "44R", "46R", "38L", "40L", "42L"],
    description:
      "Complete three-piece suit featuring jacket, vest and trousers for ultimate formal elegance.",
    details: [
      "Super 130s wool",
      "Peak lapel design",
      "Five-pocket vest",
      "Tapered trouser leg",
      "Includes silk pocket square",
    ],
    materials: "100% Superfine Wool",
    care: "Professional dry clean only",
    rating: 4.7,
    reviewCount: 112,
    isBestSeller: true,
  },

  // Men's Clothing - Jeans
  {
    id: 29,
    name: "Slim Fit Jeans",
    price: 79.99,
    category: "Men",
    subcategory: "Clothing",
    type: "Jeans",
    collection: "Summer 24",
    image: ex14,
    additionalImages: [ex15, ex16, ex17],
    inStock: true,
    colors: ["Dark Indigo", "Black", "Light Wash"],
    sizes: [
      "28x30",
      "28x32",
      "30x30",
      "30x32",
      "32x30",
      "32x32",
      "34x30",
      "34x32",
    ],
    description:
      "Premium stretch denim jeans with comfortable slim fit through seat and thigh.",
    details: [
      "98% cotton, 2% elastane",
      "Mid-rise waist",
      "Tapered leg opening",
      "Five-pocket styling",
      "Reinforced belt loops",
    ],
    materials: "98% Cotton, 2% Elastane",
    care: "Machine wash cold, hang dry",
    rating: 4.5,
    reviewCount: 287,
    isBestSeller: true,
  },
  {
    id: 30,
    name: "Relaxed Fit Jeans",
    price: 89.99,
    category: "Men",
    subcategory: "Clothing",
    type: "Jeans",
    collection: "Summer 24",
    image: ex15,
    additionalImages: [ex14, ex16],
    inStock: true,
    colors: ["Medium Wash", "Dark Wash", "Stone Wash"],
    sizes: [
      "30x30",
      "30x32",
      "32x30",
      "32x32",
      "34x30",
      "34x32",
      "36x30",
      "36x32",
    ],
    description:
      "Comfortable relaxed fit jeans with extra room through seat and thigh.",
    details: [
      "100% cotton denim",
      "Classic five-pocket design",
      "Double-stitched seams",
      "Button fly with zip",
      "Straight leg opening",
    ],
    materials: "100% Cotton",
    care: "Machine wash cold, tumble dry low",
    rating: 4.4,
    reviewCount: 154,
  },
  {
    id: 31,
    name: "Black Skinny Jeans",
    price: 69.99,
    category: "Men",
    subcategory: "Clothing",
    type: "Jeans",
    collection: "Summer 24",
    image: ex16,
    additionalImages: [ex14, ex15],
    inStock: true,
    colors: ["Solid Black", "Black Stretch"],
    sizes: [
      "28x30",
      "28x32",
      "30x30",
      "30x32",
      "32x30",
      "32x32",
      "34x30",
      "34x32",
    ],
    description:
      "Ultra-slim black jeans with stretch fabric for maximum comfort and style.",
    details: [
      "4-way stretch fabric",
      "Skinny through leg",
      "Low-rise waist",
      "Zipper fly",
      "Ankle-length cut",
    ],
    materials: "78% Cotton, 20% Polyester, 2% Elastane",
    care: "Wash inside out in cold water",
    rating: 4.6,
    reviewCount: 198,
  },
  {
    id: 32,
    name: "Distressed Jeans",
    price: 99.99,
    category: "Men",
    subcategory: "Clothing",
    type: "Jeans",
    collection: "Summer 24",
    image: ex17,
    additionalImages: [ex14, ex15],
    inStock: true,
    colors: ["Light Distressed", "Medium Distressed", "Heavy Distressed"],
    sizes: ["30x30", "30x32", "32x30", "32x32", "34x30", "34x32"],
    description:
      "Fashion-forward distressed jeans with authentic wear patterns and comfortable fit.",
    details: [
      "Hand-distressed detailing",
      "Slim straight leg",
      "Mid-rise waist",
      "Five-pocket styling",
      "Reinforced stress points",
    ],
    materials: "100% Cotton",
    care: "Machine wash cold, inside out",
    rating: 4.3,
    reviewCount: 87,
    isNew: true,
  },

  // Men's Clothing - Pants
  {
    id: 33,
    name: "Chino Pants",
    price: 59.99,
    category: "Men",
    subcategory: "Clothing",
    type: "Pants",
    collection: "Summer 24",
    image: ex18,
    additionalImages: [ex19, ex20],
    inStock: true,
    colors: ["Khaki", "Navy", "Olive", "Stone"],
    sizes: [
      "30x30",
      "30x32",
      "32x30",
      "32x32",
      "34x30",
      "34x32",
      "36x30",
      "36x32",
    ],
    description:
      "Classic chino pants with perfect drape and comfortable fit for business casual wear.",
    details: [
      "Twill cotton fabric",
      "Flat front design",
      "Slim straight leg",
      "Button closure with zip",
      "Two back pockets",
    ],
    materials: "100% Cotton",
    care: "Machine wash warm, tumble dry low",
    rating: 4.7,
    reviewCount: 213,
    isBestSeller: true,
  },
  {
    id: 34,
    name: "Dress Pants",
    price: 69.99,
    category: "Men",
    subcategory: "Clothing",
    type: "Pants",
    collection: "Winter 23",
    image: ex19,
    additionalImages: [ex18, ex20],
    inStock: true,
    colors: ["Black", "Charcoal", "Navy"],
    sizes: [
      "30x30",
      "30x32",
      "32x30",
      "32x32",
      "34x30",
      "34x32",
      "36x30",
      "36x32",
    ],
    description:
      "Premium dress pants with sharp crease and comfortable stretch for all-day wear.",
    details: [
      "Wool blend fabric",
      "Flat front with side tabs",
      "Knife-edge crease",
      "Hidden expandable waist",
      "Cuffed hem option",
    ],
    materials: "65% Wool, 33% Polyester, 2% Spandex",
    care: "Dry clean only",
    rating: 4.5,
    reviewCount: 147,
  },
  {
    id: 35,
    name: "Linen Pants",
    price: 49.99,
    category: "Men",
    subcategory: "Clothing",
    type: "Pants",
    collection: "Summer 24",
    image: ex20,
    additionalImages: [ex18, ex19],
    inStock: true,
    colors: ["Natural", "White", "Beige", "Light Blue"],
    sizes: ["30x30", "30x32", "32x30", "32x32", "34x30", "34x32"],
    description:
      "Breathable linen pants perfect for warm weather with relaxed yet tailored fit.",
    details: [
      "100% premium linen",
      "Drawstring waist",
      "Elastic back for comfort",
      "Side pockets",
      "Cropped ankle length",
    ],
    materials: "100% Linen",
    care: "Machine wash cold, line dry",
    rating: 4.6,
    reviewCount: 124,
  },
  {
    id: 36,
    name: "Cargo Pants",
    price: 79.99,
    category: "Men",
    subcategory: "Clothing",
    type: "Pants",
    collection: "Summer 24",
    image: ex102,
    additionalImages: [ex18, ex19],
    inStock: true,
    colors: ["Olive", "Black", "Khaki"],
    sizes: [
      "30x30",
      "30x32",
      "32x30",
      "32x32",
      "34x30",
      "34x32",
      "36x30",
      "36x32",
    ],
    description:
      "Functional cargo pants with multiple pockets and durable fabric for active wear.",
    details: [
      "Ripstop cotton blend",
      "Seven-pocket design",
      "Adjustable waist",
      "Gusseted crotch",
      "Tapered leg",
    ],
    materials: "65% Cotton, 35% Nylon",
    care: "Machine wash warm, tumble dry low",
    rating: 4.4,
    reviewCount: 89,
  },

  // Men's Clothing - Polo
  {
    id: 37,
    name: "Classic Polo Shirt",
    price: 39.99,
    originalPrice: 49.99,
    category: "Men",
    subcategory: "Clothing",
    type: "Polos",
    collection: "Summer 24",
    image: ex21,
    additionalImages: [ex22, ex23],
    inStock: true,
    colors: ["White", "Navy", "Black", "Heather Gray"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    description:
      "Essential pique polo shirt with classic fit and moisture-wicking fabric for all-day comfort.",
    details: [
      "100% premium cotton pique",
      "Three-button placket",
      "Ribbed collar with stay-stitching",
      "Side vents for mobility",
      "Taped neck and shoulders",
    ],
    materials: "100% Cotton",
    care: "Machine wash cold, tumble dry low",
    rating: 4.7,
    reviewCount: 342,
    isBestSeller: true,
  },
  {
    id: 38,
    name: "Performance Polo",
    price: 49.99,
    category: "Men",
    subcategory: "Clothing",
    type: "Polos",
    collection: "Summer 24",
    image: ex22,
    additionalImages: [ex21, ex24],
    inStock: true,
    colors: ["Royal Blue", "Charcoal", "Forest Green", "Red"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    description:
      "High-performance polo with UV protection and quick-dry technology for active lifestyles.",
    details: [
      "Moisture-wicking fabric",
      "UPF 50+ sun protection",
      "Tagless label for comfort",
      "Flatlock seams to prevent chafing",
      "Vented back panel",
    ],
    materials: "92% Polyester, 8% Spandex",
    care: "Machine wash cold, line dry",
    rating: 4.8,
    reviewCount: 215,
    isNew: true,
  },
  {
    id: 39,
    name: "Polo Shirt Pack",
    price: 99.99,
    category: "Men",
    subcategory: "Clothing",
    type: "Polos",
    collection: "Summer 24",
    image: ex23,
    additionalImages: [ex21, ex22],
    inStock: true,
    colors: [
      "Basic Pack (White/Black/Navy)",
      "Color Pack (Red/Green/Blue)",
      "Neutral Pack (Gray/Beige/White)",
    ],
    sizes: ["S", "M", "L", "XL"],
    description:
      "Value pack of three premium polo shirts in coordinating colors for versatile summer wardrobe.",
    details: [
      "Three high-quality polos",
      "Mix of classic colors",
      "Same great fit across all",
      "Bundle discount savings",
      "Perfect for travel",
    ],
    materials: "100% Cotton",
    care: "Machine wash cold, tumble dry low",
    rating: 4.6,
    reviewCount: 178,
  },
  {
    id: 40,
    name: "Linen Polo Shirt",
    price: 44.99,
    category: "Men",
    subcategory: "Clothing",
    type: "Polos",
    collection: "Summer 24",
    image: ex24,
    additionalImages: [ex21, ex25],
    inStock: true,
    colors: ["Natural", "Sky Blue", "Sage Green"],
    sizes: ["S", "M", "L"],
    description:
      "Breathable linen polo with relaxed fit perfect for warm weather sophistication.",
    details: [
      "100% premium linen",
      "Unstructured collar",
      "Mother-of-pearl buttons",
      "Slightly longer back hem",
      "Natural wrinkle texture",
    ],
    materials: "100% Linen",
    care: "Machine wash cold, line dry",
    rating: 4.5,
    reviewCount: 92,
  },
  {
    id: 41,
    name: "Designer Polo",
    price: 79.99,
    category: "Men",
    subcategory: "Clothing",
    type: "Polos",
    collection: "Summer 24",
    image: ex25,
    additionalImages: [ex21, ex22],
    inStock: true,
    colors: ["Midnight Navy", "Racing Green", "Burgundy"],
    sizes: ["S", "M", "L", "XL"],
    description:
      "Luxury polo shirt with signature embroidery and premium fabric for elevated casual style.",
    details: [
      "Pima cotton blend",
      "Contrast inner placket",
      "Signature embroidered logo",
      "Perfect mid-weight fabric",
      "Slim European fit",
    ],
    materials: "85% Pima Cotton, 15% Silk",
    care: "Dry clean recommended",
    rating: 4.9,
    reviewCount: 156,
    isBestSeller: true,
  },

  // Men's Clothing - Shirts
  {
    id: 42,
    name: "Dress Shirt",
    price: 49.99,
    category: "Men",
    subcategory: "Clothing",
    type: "Shirts",
    collection: "Winter 23",
    image: ex26,
    additionalImages: [ex27, ex42],
    inStock: true,
    colors: ["White", "Light Blue", "Pale Pink"],
    sizes: ["15/32", "15.5/33", "16/33", "16.5/34", "17/34", "17.5/35"],
    description:
      "Classic dress shirt with semi-spread collar and single cuff for professional occasions.",
    details: [
      "Non-iron cotton fabric",
      "Semi-spread collar",
      "Single button cuff",
      "Darted back for fit",
      "Split yoke construction",
    ],
    materials: "100% Cotton",
    care: "Machine wash warm, tumble dry low",
    rating: 4.6,
    reviewCount: 287,
  },
  {
    id: 43,
    name: "Oxford Shirt",
    price: 59.99,
    category: "Men",
    subcategory: "Clothing",
    type: "Shirts",
    collection: "Winter 23",
    image: ex27,
    additionalImages: [ex26, ex42],
    inStock: true,
    colors: ["Blue Oxford", "Gray Oxford", "White Oxford"],
    sizes: ["S", "M", "L", "XL"],
    description:
      "Substantial oxford cloth button-down shirt with roll-up sleeves for smart casual wear.",
    details: [
      "Heavyweight oxford cloth",
      "Button-down collar",
      "Roll-up sleeve tabs",
      "Two-button barrel cuffs",
      "Curved hem for tucking",
    ],
    materials: "100% Cotton Oxford",
    care: "Machine wash warm, tumble dry low",
    rating: 4.7,
    reviewCount: 198,
    isBestSeller: true,
  },

  // Men's Clothing - Sweatshirts & Hoodies
  {
    id: 44,
    name: "Zip Hoodie",
    price: 69.99,
    category: "Men",
    subcategory: "Clothing",
    type: "Sweatshirts & Hoodies",
    collection: "Winter 23",
    image: ex28,
    additionalImages: [ex29, ex30],
    inStock: true,
    colors: ["Black", "Heather Gray", "Navy"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    description:
      "Premium zip-up hoodie with fleece lining and adjustable drawstring hood for cool weather.",
    details: [
      "Brushed interior fleece",
      "Kangaroo pocket",
      "Ribbed cuffs and hem",
      "Metal zipper with pull",
      "Double-lined hood",
    ],
    materials: "80% Cotton, 20% Polyester",
    care: "Machine wash cold, tumble dry low",
    rating: 4.8,
    reviewCount: 324,
    isBestSeller: true,
  },
  {
    id: 45,
    name: "Pullover Hoodie",
    price: 59.99,
    category: "Men",
    subcategory: "Clothing",
    type: "Sweatshirts & Hoodies",
    collection: "Winter 23",
    image: ex29,
    additionalImages: [ex28, ex30],
    inStock: true,
    colors: ["Charcoal", "Olive Green", "Burgundy"],
    sizes: ["S", "M", "L", "XL"],
    description:
      "Classic pullover hoodie with soft fleece interior and adjustable drawstring hood.",
    details: [
      "Heavyweight cotton blend",
      "Front pouch pocket",
      "Double-lined hood",
      "Coverstitched seams",
      "Relaxed fit",
    ],
    materials: "70% Cotton, 30% Polyester",
    care: "Machine wash cold, tumble dry low",
    rating: 4.6,
    reviewCount: 276,
  },
  {
    id: 46,
    name: "Crewneck Sweatshirt",
    price: 49.99,
    category: "Men",
    subcategory: "Clothing",
    type: "Sweatshirts & Hoodies",
    collection: "Winter 23",
    image: ex30,
    additionalImages: [ex28, ex29],
    inStock: true,
    colors: ["Black", "White", "Heather Gray"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    description:
      "Essential crewneck sweatshirt with ribbed trim for timeless casual style.",
    details: [
      "Mid-weight French terry",
      "Set-in sleeves",
      "Tubular construction",
      "Double-needle stitching",
      "Layering perfect",
    ],
    materials: "100% Cotton",
    care: "Machine wash cold, tumble dry low",
    rating: 4.7,
    reviewCount: 412,
  },
  {
    id: 47,
    name: "Graphic Hoodie",
    price: 79.99,
    category: "Men",
    subcategory: "Clothing",
    type: "Sweatshirts & Hoodies",
    collection: "Winter 23",
    image: ex31,
    additionalImages: [ex28, ex29],
    inStock: true,
    colors: ["Black/White", "Navy/Gold", "Gray/Black"],
    sizes: ["S", "M", "L"],
    description:
      "Statement graphic hoodie with artist-designed print and premium fleece lining.",
    details: [
      "Screen-printed graphic",
      "Heavyweight 12oz fleece",
      "Adjustable drawcord",
      "Kangaroo pocket",
      "Slim fit",
    ],
    materials: "80% Cotton, 20% Polyester",
    care: "Wash inside out in cold water",
    rating: 4.5,
    reviewCount: 187,
    isNew: true,
  },
  {
    id: 48,
    name: "Fleece Sweatshirt",
    price: 54.99,
    category: "Men",
    subcategory: "Clothing",
    type: "Sweatshirts & Hoodies",
    collection: "Winter 23",
    image: ex32,
    additionalImages: [ex28, ex30],
    inStock: true,
    colors: ["Navy", "Charcoal", "Camel"],
    sizes: ["S", "M", "L", "XL"],
    description:
      "Ultra-soft fleece sweatshirt with thermal properties for cold weather comfort.",
    details: [
      "300gsm fleece",
      "Raglan sleeves",
      "Contrast inner collar",
      "Flatlock seams",
      "Relaxed fit",
    ],
    materials: "100% Polyester Fleece",
    care: "Machine wash cold, line dry",
    rating: 4.6,
    reviewCount: 143,
  },

  // Men's Clothing - T-Shirts
  {
    id: 49,
    name: "Basic T-Shirt",
    price: 24.99,
    category: "Men",
    subcategory: "Clothing",
    type: "T-Shirts",
    collection: "Summer 24",
    image: ex33,
    additionalImages: [ex34, ex49],
    inStock: true,
    colors: ["White", "Black", "Heather Gray", "Navy"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    description:
      "Essential crewneck tee made from premium combed cotton for everyday comfort.",
    details: [
      "Combed cotton jersey",
      "Tubular construction",
      "Shoulder-to-shoulder tape",
      "Double-needle stitching",
      "Classic fit",
    ],
    materials: "100% Cotton",
    care: "Machine wash cold, tumble dry low",
    rating: 4.7,
    reviewCount: 528,
    isBestSeller: true,
  },
  {
    id: 50,
    name: "V-Neck T-Shirt",
    price: 29.99,
    category: "Men",
    subcategory: "Clothing",
    type: "T-Shirts",
    collection: "Summer 24",
    image: ex34,
    additionalImages: [ex33, ex49],
    inStock: true,
    colors: ["White", "Black", "Charcoal", "Burgundy"],
    sizes: ["S", "M", "L", "XL"],
    description:
      "Soft v-neck tee with slightly deeper neckline for stylish layering options.",
    details: [
      "Premium ring-spun cotton",
      "Contrast neck tape",
      "Side seams",
      "Tear-away label",
      "Slimmer fit",
    ],
    materials: "100% Cotton",
    care: "Machine wash cold, tumble dry low",
    rating: 4.6,
    reviewCount: 387,
  },

  // Men's Clothing - TUXEDOS
  {
    id: 51,
    name: "Classic Tuxedo",
    price: 599.99,
    originalPrice: 699.99,
    category: "Men",
    subcategory: "Clothing",
    type: "Tuxedos",
    collection: "Summer 24",
    image: pd35,
    additionalImages: [pd36, pd37],
    inStock: true,
    colors: ["Black", "Midnight Blue"],
    sizes: ["38R", "40R", "42R", "44R", "46R", "38L", "40L", "42L"],
    description:
      "Timeless black-tie tuxedo with satin lapels and matching trousers for formal occasions.",
    details: [
      "Peak lapel with satin facing",
      "Single-button closure",
      "Satin stripe trouser",
      "Includes matching vest",
      "Functional sleeve buttons",
    ],
    materials: "Super 110s Wool, Satin Accents",
    care: "Professional dry clean only",
    rating: 4.9,
    reviewCount: 87,
    isBestSeller: true,
  },
  {
    id: 52,
    name: "Slim Fit Tuxedo",
    price: 649.99,
    category: "Men",
    subcategory: "Clothing",
    type: "Tuxedos",
    collection: "Winter 23",
    image: pd37,
    additionalImages: [pd35, pd36],
    inStock: true,
    colors: ["Black", "Charcoal"],
    sizes: ["38R", "40R", "42R", "44R", "38L", "40L"],
    description:
      "Modern slim-fit tuxedo with contemporary styling for fashion-forward formalwear.",
    details: [
      "Slim notch lapel",
      "Two-button closure",
      "Higher armholes",
      "Tapered trousers",
      "Includes satin bow tie",
    ],
    materials: "97% Wool, 3% Elastane",
    care: "Professional dry clean only",
    rating: 4.8,
    reviewCount: 64,
    isNew: true,
  },
  {
    id: 53,
    name: "Black Tie Tuxedo",
    price: 699.99,
    category: "Men",
    subcategory: "Clothing",
    type: "Tuxedos",
    collection: "Winter 23",
    image: pd36,
    additionalImages: [pd35, pd37],
    inStock: true,
    colors: ["Jet Black"],
    sizes: ["38R", "40R", "42R", "44R", "46R", "38L", "40L", "42L"],
    description:
      "Ultra-formal tuxedo with shawl collar and satin details for black-tie events.",
    details: [
      "Shawl collar design",
      "Single-button closure",
      "Satin-covered buttons",
      "Side-adjuster trousers",
      "Includes cummerbund",
    ],
    materials: "Super 120s Wool, Silk Satin",
    care: "Professional dry clean only",
    rating: 4.9,
    reviewCount: 53,
  },

  // Men's Clothing - WAISTCOATS
  {
    id: 54,
    name: "Slim Waistcoat",
    price: 129.99,
    category: "Men",
    subcategory: "Clothing",
    type: "Waistcoats",
    collection: "Winter 23",
    image: ex36,
    additionalImages: [ex37, ex38],
    inStock: true,
    colors: ["Black", "Gray", "Navy"],
    sizes: ["S (34-36)", "M (38-40)", "L (42-44)", "XL (46-48)"],
    description:
      "Tailored slim-fit waistcoat with back adjusters for perfect formal layering.",
    details: [
      "Five-button front",
      "Notched bottom",
      "Adjustable back strap",
      "Four welt pockets",
      "Contrast lining",
    ],
    materials: "65% Wool, 35% Polyester",
    care: "Dry clean only",
    rating: 4.6,
    reviewCount: 78,
  },
  {
    id: 55,
    name: "Formal Waistcoat",
    price: 149.99,
    category: "Men",
    subcategory: "Clothing",
    type: "Waistcoats",
    collection: "Winter 23",
    image: ex37,
    additionalImages: [ex36, ex38],
    inStock: true,
    colors: ["Black", "Ivory", "Burgundy"],
    sizes: ["S", "M", "L", "XL"],
    description:
      "Traditional formal waistcoat with satin back for three-piece suit completion.",
    details: [
      "Six-button front",
      "Pointed bottom",
      "Satin back panel",
      "Three welt pockets",
      "Hook-and-eye closure",
    ],
    materials: "100% Wool",
    care: "Dry clean only",
    rating: 4.7,
    reviewCount: 92,
  },
  {
    id: 56,
    name: "Three-piece Waistcoat",
    price: 159.99,
    category: "Men",
    subcategory: "Clothing",
    type: "Waistcoats",
    collection: "Winter 23",
    image: ex38,
    additionalImages: [ex36, ex37],
    inStock: true,
    colors: ["Charcoal", "Navy", "Black"],
    sizes: ["S", "M", "L", "XL"],
    description:
      "Matching waistcoat designed to complete your three-piece suit ensemble.",
    details: [
      "Same fabric as suit",
      "Five-button front",
      "Adjustable back",
      "Dual welt pockets",
      "Contrast inner lining",
    ],
    materials: "Varies by suit fabric",
    care: "Same as matching suit",
    rating: 4.8,
    reviewCount: 65,
    isBestSeller: true,
  },

  // Women's Accessories - Eyewear
  {
    id: 57,
    name: "Designer Sunglasses",
    price: 129.99,
    category: "Women",
    subcategory: "Accessories",
    type: "Eyewear",
    collection: "Summer 24",
    image: ex39,
    additionalImages: [ex40, ex41],
    inStock: true,
    colors: ["Black/Gold", "Tortoise", "Silver"],
    description:
      "Luxury acetate sunglasses with polarized lenses and designer detailing.",
    details: [
      "100% UV protection",
      "Polarized lenses",
      "Acetate frames",
      "Signature temple design",
      "Includes microfiber pouch",
    ],
    materials: "Acetate frame, Polycarbonate lenses",
    care: "Clean with microfiber cloth, store in case",
    rating: 4.7,
    reviewCount: 214,
    isBestSeller: true,
  },
  {
    id: 58,
    name: "Cat Eye Sunglasses",
    price: 99.99,
    category: "Women",
    subcategory: "Accessories",
    type: "Eyewear",
    collection: "Summer 24",
    image: ex40,
    additionalImages: [ex39, ex42],
    inStock: true,
    colors: ["Black", "Tortoise", "Red"],
    description:
      "Retro-inspired cat eye sunglasses with vintage charm and modern UV protection.",
    details: [
      "UV400 protection",
      "Metal-accented corners",
      "Lightweight frame",
      "Spring hinges",
      "Includes hard case",
    ],
    materials: "Acetate frame, Glass lenses",
    care: "Clean with lens cleaner, avoid heat",
    rating: 4.6,
    reviewCount: 187,
  },
  {
    id: 59,
    name: "Aviator Sunglasses",
    price: 89.99,
    category: "Women",
    subcategory: "Accessories",
    type: "Eyewear",
    collection: "Summer 24",
    image: ex41,
    additionalImages: [ex39, ex40],
    inStock: true,
    colors: ["Gold/Green", "Silver/Gray", "Rose Gold/Brown"],
    description:
      "Classic aviator sunglasses with gradient lenses and lightweight metal frame.",
    details: [
      "Mirrored gradient lenses",
      "Adjustable nose pads",
      "Double bridge design",
      "Spring hinges",
      "Includes cleaning cloth",
    ],
    materials: "Stainless steel frame, Polycarbonate lenses",
    care: "Rinse with water before wiping",
    rating: 4.8,
    reviewCount: 256,
  },
  {
    id: 60,
    name: "Oversized Sunglasses",
    price: 79.99,
    category: "Women",
    subcategory: "Accessories",
    type: "Eyewear",
    collection: "Summer 24",
    image: ex42,
    additionalImages: [ex39, ex41],
    inStock: true,
    colors: ["Black", "Tortoise", "White"],
    description:
      "Fashion-forward oversized sunglasses with full UV protection and statement-making style.",
    details: [
      "100% UV protection",
      "Oversized square frames",
      "Subtle branding",
      "Comfortable nose pads",
      "Includes storage pouch",
    ],
    materials: "Acetate frame, Polycarbonate lenses",
    care: "Store in protective case when not in use",
    rating: 4.5,
    reviewCount: 143,
    isNew: true,
  },

  // Women's Accessories - Gifts for her
  {
    id: 61,
    name: "Leather Clutch",
    price: 89.99,
    category: "Women",
    subcategory: "Accessories",
    type: "Gifts for her",
    collection: "Ready to wear",
    image: ex43,
    additionalImages: [ex44, ex45],
    inStock: true,
    colors: ["Black", "Cognac", "Burgundy"],
    description:
      "Structured leather clutch with removable chain strap for evening elegance.",
    details: [
      "Top-grain leather",
      'Removable 18" chain strap',
      "Magnetic snap closure",
      "Interior card slots",
      "Wipe-clean lining",
    ],
    materials: "100% Leather, Metal hardware",
    care: "Wipe with damp cloth, condition monthly",
    rating: 4.7,
    reviewCount: 98,
  },
  {
    id: 62,
    name: "Silk Scarf",
    price: 59.99,
    category: "Women",
    subcategory: "Accessories",
    type: "Gifts for her",
    collection: "Ready to wear",
    image: ex44,
    additionalImages: [ex43, ex46],
    inStock: true,
    colors: ["Floral Print", "Abstract", "Geometric"],
    description:
      "Luxury silk twill scarf with hand-rolled edges and vibrant prints.",
    details: [
      "100% pure silk",
      '34" x 34" square',
      "Hand-rolled edges",
      "Signature artist prints",
      "Gift box included",
    ],
    materials: "100% Silk",
    care: "Dry clean or hand wash cold",
    rating: 4.8,
    reviewCount: 132,
    isBestSeller: true,
  },
  {
    id: 63,
    name: "Perfume Set",
    price: 129.99,
    category: "Women",
    subcategory: "Accessories",
    type: "Gifts for her",
    collection: "Ready to wear",
    image: ex45,
    additionalImages: [ex43, ex46],
    inStock: true,
    description:
      "Luxury fragrance trio with day, evening and special occasion scents.",
    details: [
      "Three 0.5oz travel sprays",
      "Distinct scent profiles",
      "Velvet pouch included",
      "Gift-ready packaging",
      "Signature fragrances",
    ],
    materials: "Alcohol, Fragrance oils",
    care: "Store away from heat and light",
    rating: 4.9,
    reviewCount: 87,
  },
  {
    id: 64,
    name: "Jewelry Box",
    price: 79.99,
    category: "Women",
    subcategory: "Accessories",
    type: "Gifts for her",
    collection: "Ready to wear",
    image: ex46,
    additionalImages: [ex43, ex45],
    inStock: true,
    colors: ["White", "Pink", "Walnut"],
    description:
      "Velvet-lined jewelry organizer with multiple compartments and locking mechanism.",
    details: [
      "Wood construction",
      "Plush velvet lining",
      "Lock and key included",
      "Ring rolls and earring holders",
      "Mirror inside lid",
    ],
    materials: "MDF wood, Velvet lining",
    care: "Dust with dry cloth",
    rating: 4.6,
    reviewCount: 112,
  },

  // Women's Accessories - Hats & Scarves
  {
    id: 65,
    name: "Wide Brim Hat",
    price: 49.99,
    category: "Women",
    subcategory: "Accessories",
    type: "Hats & Scarves",
    collection: "Summer 24",
    image: ex47,
    additionalImages: [ex48, ex50],
    inStock: true,
    colors: ["Natural", "Black", "Straw"],
    sizes: ["One Size"],
    description:
      "Elegant wide-brim sun hat with UPF protection and adjustable inner band.",
    details: [
      '3.5" brim circumference',
      "UPF 50+ protection",
      "Adjustable inner drawstring",
      "Breathable cotton lining",
      "Packable design",
    ],
    materials: "Paper straw, Cotton lining",
    care: "Spot clean only, reshape when damp",
    rating: 4.7,
    reviewCount: 156,
  },
  {
    id: 66,
    name: "Cashmere Scarf",
    price: 89.99,
    category: "Women",
    subcategory: "Accessories",
    type: "Hats & Scarves",
    collection: "Winter 23",
    image: ex48,
    additionalImages: [ex47, ex51],
    inStock: true,
    colors: ["Camel", "Gray", "Rose"],
    description:
      "Luxury cashmere scarf with fringed ends and lightweight warmth.",
    details: [
      "100% pure cashmere",
      '12" x 72" dimensions',
      "Hand-finished fringe",
      "Lightweight yet warm",
      "Gift box available",
    ],
    materials: "100% Cashmere",
    care: "Hand wash cold, lay flat to dry",
    rating: 4.9,
    reviewCount: 203,
    isBestSeller: true,
  },
  {
    id: 67,
    name: "Beanie Hat",
    price: 29.99,
    category: "Women",
    subcategory: "Accessories",
    type: "Hats & Scarves",
    collection: "Winter 23",
    image: ex49,
    additionalImages: [ex48, ex51],
    inStock: true,
    colors: ["Black", "Cream", "Heather Gray"],
    sizes: ["One Size"],
    description:
      "Slouchy knit beanie with fold-up brim for adjustable coverage.",
    details: [
      "Acrylic/wool blend",
      "Slouchy silhouette",
      "Fold-up brim",
      "Unisex sizing",
      "Hand-wash only",
    ],
    materials: "70% Acrylic, 30% Wool",
    care: "Hand wash cold, lay flat to dry",
    rating: 4.5,
    reviewCount: 287,
  },
  {
    id: 68,
    name: "Fedora Hat",
    price: 39.99,
    category: "Women",
    subcategory: "Accessories",
    type: "Hats & Scarves",
    collection: "Summer 24",
    image: ex50,
    additionalImages: [ex47, ex49],
    inStock: true,
    colors: ["Black", "Brown", "Navy"],
    sizes: ["One Size"],
    description:
      'Classic fedora with pinched crown and 2.5" brim for timeless style.',
    details: [
      "Wool felt construction",
      '2.5" snap brim',
      "Leather hatband",
      "Inner sweatband",
      "Packable design",
    ],
    materials: "100% Wool felt",
    care: "Brush with hat brush, spot clean",
    rating: 4.6,
    reviewCount: 178,
  },
  {
    id: 69,
    name: "Pashmina Shawl",
    price: 69.99,
    category: "Women",
    subcategory: "Accessories",
    type: "Hats & Scarves",
    collection: "Winter 23",
    image: ex51,
    additionalImages: [ex48, ex66],
    inStock: true,
    colors: ["Ivory", "Charcoal", "Burgundy"],
    description:
      "Luxury pashmina wrap with hand-rolled edges for elegant layering.",
    details: [
      "70% Pashmina, 30% Silk",
      '28" x 80" dimensions',
      "Hand-rolled edges",
      "Lightweight warmth",
      "Versatile styling",
    ],
    materials: "70% Pashmina, 30% Silk",
    care: "Dry clean recommended",
    rating: 4.8,
    reviewCount: 145,
  },

  // Women's Accessories - Hosiery
  {
    id: 70,
    name: "Sheer Tights",
    price: 19.99,
    category: "Women",
    subcategory: "Accessories",
    type: "Hosiery",
    collection: "Winter 23",
    image: ex52,
    additionalImages: [ex53, ex54],
    inStock: true,
    colors: ["Nude", "Black", "Suntan"],
    sizes: ["S/M (4-8)", "L/XL (10-14)"],
    description:
      "Ultra-sheer tights with reinforced toes and comfortable waistband.",
    details: [
      "15 denier sheerness",
      "Reinforced toes",
      "Cotton gusset",
      "Comfortable waistband",
      "Non-run technology",
    ],
    materials: "90% Nylon, 10% Spandex",
    care: "Hand wash cold, line dry",
    rating: 4.4,
    reviewCount: 342,
    isBestSeller: true,
  },
  {
    id: 71,
    name: "Patterned Tights",
    price: 24.99,
    category: "Women",
    subcategory: "Accessories",
    type: "Hosiery",
    collection: "Winter 23",
    image: ex53,
    additionalImages: [ex52, ex54],
    inStock: true,
    colors: ["Floral", "Polka Dot", "Striped"],
    sizes: ["S/M", "L/XL"],
    description: "Fashion tights with playful patterns and comfortable fit.",
    details: [
      "40 denier opacity",
      "Stretch patterns",
      "Reinforced toes",
      "Wide waistband",
      "Matte finish",
    ],
    materials: "88% Nylon, 12% Spandex",
    care: "Machine wash cold, line dry",
    rating: 4.5,
    reviewCount: 198,
  },
  {
    id: 72,
    name: "Woolen Tights",
    price: 29.99,
    category: "Women",
    subcategory: "Accessories",
    type: "Hosiery",
    collection: "Winter 23",
    image: ex54,
    additionalImages: [ex52, ex53],
    inStock: true,
    colors: ["Black", "Charcoal", "Navy"],
    sizes: ["S/M", "L/XL"],
    description:
      "Warm wool-blend tights with thermal properties for cold weather.",
    details: [
      "Merino wool blend",
      "Thermal insulation",
      "Flat seams",
      "Wide comfort waistband",
      "Opaque coverage",
    ],
    materials: "70% Merino Wool, 25% Nylon, 5% Spandex",
    care: "Hand wash cold, lay flat to dry",
    rating: 4.7,
    reviewCount: 156,
    isNew: true,
  },

  // Women's Accessories - Jewelry
  {
    id: 73,
    name: "Pearl Necklace",
    price: 149.99,
    category: "Women",
    subcategory: "Accessories",
    type: "Jewelry",
    collection: "Minimalism and fantasy",
    image: ex55,
    additionalImages: [ex56, ex57],
    inStock: true,
    colors: ["White", "Black"],
    description:
      "Elegant freshwater pearl necklace with sterling silver clasp.",
    details: [
      "6-7mm freshwater pearls",
      '18" sterling silver chain',
      "Lobster clasp closure",
      "Gift box included",
      "Hypoallergenic",
    ],
    materials: "Freshwater pearls, Sterling silver",
    care: "Wipe with soft cloth after wear",
    rating: 4.8,
    reviewCount: 112,
    isBestSeller: true,
  },
  {
    id: 74,
    name: "Diamond Studs",
    price: 199.99,
    category: "Women",
    subcategory: "Accessories",
    type: "Jewelry",
    collection: "Minimalism and fantasy",
    image: ex56,
    additionalImages: [ex55, ex57],
    inStock: true,
    colors: ["White Gold", "Yellow Gold"],
    description:
      "Classic round-cut diamond stud earrings in precious metal settings.",
    details: [
      "0.25ct total weight",
      "Four-prong setting",
      "Screw-back closure",
      "Certified conflict-free diamonds",
      "Gift box included",
    ],
    materials: "14K gold, Diamonds",
    care: "Clean with jewelry polishing cloth",
    rating: 4.9,
    reviewCount: 89,
  },
  {
    id: 75,
    name: "Gold Bangle",
    price: 129.99,
    category: "Women",
    subcategory: "Accessories",
    type: "Jewelry",
    collection: "Minimalism and fantasy",
    image: ex57,
    additionalImages: [ex55, ex56],
    inStock: true,
    colors: ["Yellow Gold", "Rose Gold"],
    sizes: ['Small (6")', 'Medium (7")', 'Large (8")'],
    description:
      "Minimalist gold-plated bangle bracelet with subtle hammered texture.",
    details: [
      "Gold-plated brass",
      "Hammered finish",
      "Hinged closure",
      "2mm width",
      "Gift box included",
    ],
    materials: "Brass with 18K gold plating",
    care: "Remove before swimming/showering",
    rating: 4.7,
    reviewCount: 76,
  },
  {
    id: 76,
    name: "Statement Earrings",
    price: 59.99,
    category: "Women",
    subcategory: "Accessories",
    type: "Jewelry",
    collection: "Minimalism and fantasy",
    image: ex58,
    additionalImages: [ex59, ex60],
    inStock: true,
    colors: ["Gold/Black", "Silver/Blue", "Rose Gold/Clear"],
    description:
      "Geometric statement earrings with crystal accents for bold looks.",
    details: [
      '2.5" drop length',
      "Surgical steel posts",
      "Lightweight design",
      "Crystal embellishments",
      "Secure butterfly backs",
    ],
    materials: "Alloy, Crystals",
    care: "Store separately to prevent scratching",
    rating: 4.6,
    reviewCount: 134,
    isNew: true,
  },
  {
    id: 77,
    name: "Charm Bracelet",
    price: 89.99,
    category: "Women",
    subcategory: "Accessories",
    type: "Jewelry",
    collection: "Minimalism and fantasy",
    image: ex59,
    additionalImages: [ex58, ex60],
    inStock: true,
    colors: ["Silver", "Gold"],
    description:
      "Personalizable charm bracelet with delicate chain and signature charms.",
    details: [
      '7" adjustable length',
      "Three initial charms included",
      "Lobster clasp closure",
      "Additional charms sold separately",
      "Gift box included",
    ],
    materials: "Sterling silver or Gold-plated brass",
    care: "Polish with jewelry cloth regularly",
    rating: 4.5,
    reviewCount: 98,
  },
  {
    id: 78,
    name: "Stacking Rings",
    price: 49.99,
    category: "Women",
    subcategory: "Accessories",
    type: "Jewelry",
    collection: "Minimalism and fantasy",
    image: ex60,
    additionalImages: [ex58, ex59],
    inStock: true,
    colors: ["Mixed Metals", "Rose Gold", "Silver"],
    sizes: ["4-9"],
    description: "Set of three thin stacking rings for layered finger styling.",
    details: [
      "Three rings per set",
      "1mm band width",
      "Mix of plain and textured",
      "Sizes can be mixed",
      "Gift pouch included",
    ],
    materials: "Sterling silver or Gold-plated brass",
    care: "Store in separate compartments",
    rating: 4.7,
    reviewCount: 156,
  },

  // Women's Clothing - Dresses
  {
    id: 79,
    name: "Summer Floral Dress",
    price: 89.99,
    originalPrice: 109.99,
    category: "Women",
    subcategory: "Clothing",
    type: "Dresses",
    collection: "Summer 24",
    image: ex61,
    additionalImages: [ex62, ex63],
    inStock: true,
    colors: ["Blue Floral", "Pink Floral", "Yellow Floral"],
    sizes: ["XS", "S", "M", "L"],
    description:
      "Lightweight floral sundress with smocked bodice and puff sleeves.",
    details: [
      "100% cotton voile",
      "Smocked elastic bodice",
      "Puff short sleeves",
      "A-line silhouette",
      "Above-knee length",
    ],
    materials: "100% Cotton",
    care: "Machine wash cold, hang to dry",
    rating: 4.8,
    reviewCount: 234,
    isBestSeller: true,
  },
  {
    id: 80,
    name: "Cocktail Dress",
    price: 119.99,
    category: "Women",
    subcategory: "Clothing",
    type: "Dresses",
    collection: "Pre Fall 23",
    image: ex62,
    additionalImages: [ex61, ex64],
    inStock: true,
    colors: ["Black", "Emerald Green", "Navy"],
    sizes: ["XS", "S", "M"],
    description:
      "Sleeveless cocktail dress with draped neckline and fitted silhouette.",
    details: [
      "Stretch crepe fabric",
      "V-neck with draping",
      "Hidden back zipper",
      "Knee-length",
      "Lined bodice",
    ],
    materials: "95% Polyester, 5% Spandex",
    care: "Dry clean recommended",
    rating: 4.7,
    reviewCount: 187,
  },
  {
    id: 81,
    name: "Maxi Dress",
    price: 99.99,
    category: "Women",
    subcategory: "Clothing",
    type: "Dresses",
    collection: "Summer 24",
    image: ex63,
    additionalImages: [ex61, ex64],
    inStock: true,
    colors: ["White", "Red", "Black"],
    sizes: ["S", "M", "L"],
    description:
      "Flowy bohemian maxi dress with tiered skirt and adjustable straps.",
    details: [
      "Chiffon overlay",
      "Adjustable spaghetti straps",
      "Elasticated waist",
      "Three-tiered skirt",
      "Ankle-length",
    ],
    materials: "100% Polyester",
    care: "Hand wash cold, line dry",
    rating: 4.6,
    reviewCount: 156,
  },
  {
    id: 82,
    name: "Wrap Dress",
    price: 79.99,
    category: "Women",
    subcategory: "Clothing",
    type: "Dresses",
    collection: "Summer 24",
    image: ex64,
    additionalImages: [ex61, ex63],
    inStock: true,
    colors: ["Navy/White", "Black/Red", "Solid Black"],
    sizes: ["XS", "S", "M", "L"],
    description:
      "Classic wrap dress with self-tie waist and flattering V-neckline.",
    details: [
      "Jersey knit fabric",
      "Self-tie waist sash",
      "3/4 length sleeves",
      "Knee-length",
      "All-over print options",
    ],
    materials: "95% Viscose, 5% Elastane",
    care: "Machine wash cold, tumble dry low",
    rating: 4.9,
    reviewCount: 278,
    isNew: true,
  },

  // Women's Clothing - Denim
  {
    id: 83,
    name: "Skinny Jeans",
    price: 79.99,
    originalPrice: 89.99,
    category: "Women",
    subcategory: "Clothing",
    type: "Denim",
    collection: "Summer 24",
    image: ex65,
    additionalImages: [ex66, ex67],
    inStock: true,
    colors: ["Mid Blue", "Black", "Light Wash"],
    sizes: ["24", "26", "28", "30"],
    description:
      "Classic skinny jeans with stretch for all-day comfort and sleek silhouette.",
    details: [
      "High-rise waist",
      "Ankle-length",
      "4-pocket styling",
      "Stretch denim",
      "Zip and button closure",
    ],
    materials: "78% Cotton, 20% Polyester, 2% Elastane",
    care: "Machine wash cold, tumble dry low",
    rating: 4.7,
    reviewCount: 342,
    isBestSeller: true,
  },
  {
    id: 84,
    name: "Boyfriend Jeans",
    price: 89.99,
    category: "Women",
    subcategory: "Clothing",
    type: "Denim",
    collection: "Summer 24",
    image: ex66,
    additionalImages: [ex65, ex68],
    inStock: true,
    colors: ["Medium Wash", "Dark Wash", "Distressed"],
    sizes: ["26", "28", "30"],
    description:
      "Relaxed boyfriend jeans with slouchy fit and rolled cuff detailing.",
    details: [
      "Mid-rise waist",
      "Loose leg opening",
      "Distressed detailing",
      "5-pocket styling",
      "Button fly",
    ],
    materials: "100% Cotton",
    care: "Machine wash cold, hang to dry",
    rating: 4.6,
    reviewCount: 287,
  },
  {
    id: 85,
    name: "High-Waisted Jeans",
    price: 94.99,
    category: "Women",
    subcategory: "Clothing",
    type: "Denim",
    collection: "Summer 24",
    image: ex67,
    additionalImages: [ex65, ex66],
    inStock: true,
    colors: ["Black", "Dark Indigo", "White"],
    sizes: ["24", "26", "28", "30"],
    description:
      "Flattering high-waisted jeans with sculpting fit and vintage-inspired wash.",
    details: [
      '11" rise',
      "Straight leg",
      "Contour waistband",
      "No-gap design",
      "Zip and button closure",
    ],
    materials: "81% Cotton, 17% Polyester, 2% Elastane",
    care: "Machine wash cold, line dry",
    rating: 4.8,
    reviewCount: 198,
    isNew: true,
  },
  {
    id: 86,
    name: "Denim Jacket",
    price: 109.99,
    category: "Women",
    subcategory: "Clothing",
    type: "Denim",
    collection: "Summer 24",
    image: ex68,
    additionalImages: [ex66, ex67],
    inStock: true,
    colors: ["Classic Blue", "Black", "Overdyed"],
    sizes: ["XS", "S", "M", "L"],
    description:
      "Timeless denim jacket with cropped fit and modern hardware details.",
    details: [
      "Cropped silhouette",
      "Point collar",
      "Button-front closure",
      "Chest flap pockets",
      "Adjustable waist tabs",
    ],
    materials: "100% Cotton denim",
    care: "Machine wash cold, hang to dry",
    rating: 4.7,
    reviewCount: 176,
  },

  // Women's Clothing - Gowns
  {
    id: 87,
    name: "Evening Gown",
    price: 299.99,
    category: "Women",
    subcategory: "Clothing",
    type: "Gowns",
    collection: "Pre Fall 23",
    image: ex69,
    additionalImages: [ex70, ex71],
    inStock: true,
    colors: ["Emerald Green", "Navy", "Burgundy"],
    sizes: ["XS", "S", "M", "L"],
    description:
      "Elegant floor-length evening gown with draped bodice and flowing skirt.",
    details: [
      "V-neckline",
      "Surplice bodice",
      "Hidden back zipper",
      "Fully lined",
      "Train detailing",
    ],
    materials: "95% Polyester, 5% Spandex",
    care: "Professional dry clean only",
    rating: 4.9,
    reviewCount: 87,
  },
  {
    id: 88,
    name: "Bridal Gown",
    price: 599.99,
    category: "Women",
    subcategory: "Clothing",
    type: "Gowns",
    collection: "Pre Fall 23",
    image: ex70,
    additionalImages: [ex69, ex72],
    inStock: true,
    colors: ["Ivory", "White"],
    sizes: ["S", "M", "L"],
    description:
      "Romantic A-line wedding dress with lace appliqués and cathedral train.",
    details: [
      "Illusion neckline",
      "Lace bodice",
      "Chapel-length train",
      "Beaded detailing",
      "Covered button back",
    ],
    materials: "Lace overlay, Silk satin underlay",
    care: "Professional bridal preservation cleaning",
    rating: 5.0,
    reviewCount: 45,
    isBestSeller: true,
  },

  // Women's Clothing - Jackets & Coats
  {
    id: 89,
    name: "Trench Coat",
    price: 199.99,
    category: "Women",
    subcategory: "Clothing",
    type: "Jackets & Coats",
    collection: "Winter 23",
    image: ex71,
    additionalImages: [ex72, ex73],
    inStock: true,
    colors: ["Beige", "Black", "Camel"],
    sizes: ["XS", "S", "M", "L"],
    description:
      "Classic double-breasted trench coat with water-resistant finish.",
    details: [
      "Knee-length",
      "Belted waist",
      "Storm flap",
      "Gun flap detailing",
      "Button closure",
    ],
    materials: "100% Cotton gabardine",
    care: "Spot clean or professional dry clean",
    rating: 4.8,
    reviewCount: 156,
  },
  {
    id: 90,
    name: "Leather Jacket",
    price: 249.99,
    category: "Women",
    subcategory: "Clothing",
    type: "Jackets & Coats",
    collection: "Winter 23",
    image: ex72,
    additionalImages: [ex71, ex74],
    inStock: true,
    colors: ["Black", "Brown", "Burgundy"],
    sizes: ["XS", "S", "M"],
    description:
      "Biker-style leather jacket with asymmetrical zip and quilted detailing.",
    details: [
      "Asymmetrical zipper",
      "Stand collar",
      "Zippered cuffs",
      "Multiple pockets",
      "Snap-button closure",
    ],
    materials: "100% Genuine lambskin leather",
    care: "Wipe clean with damp cloth, condition regularly",
    rating: 4.9,
    reviewCount: 203,
    isNew: true,
  },
  {
    id: 91,
    name: "Wool Coat",
    price: 279.99,
    category: "Women",
    subcategory: "Clothing",
    type: "Jackets & Coats",
    collection: "Winter 23",
    image: ex73,
    additionalImages: [ex71, ex72],
    inStock: true,
    colors: ["Camel", "Gray", "Navy"],
    sizes: ["S", "M", "L"],
    description: "Warm wool-blend coat with oversized lapels and deep pockets.",
    details: [
      "Mid-thigh length",
      "Notched lapels",
      "Single-breasted",
      "Inner lining",
      "Button closure",
    ],
    materials: "80% Wool, 20% Polyester",
    care: "Professional dry clean only",
    rating: 4.7,
    reviewCount: 134,
  },
  {
    id: 92,
    name: "Puffer Jacket",
    price: 179.99,
    category: "Women",
    subcategory: "Clothing",
    type: "Jackets & Coats",
    collection: "Winter 23",
    image: ex74,
    additionalImages: [ex71, ex73],
    inStock: true,
    colors: ["Black", "Olive Green", "Bright Red"],
    sizes: ["XS", "S", "M", "L"],
    description: "Lightweight yet warm quilted puffer jacket with hood.",
    details: [
      "Water-resistant shell",
      "Removable hood",
      "Zippered pockets",
      "Elasticized cuffs",
      "Packable design",
    ],
    materials: "100% Nylon shell, 100% Polyester filling",
    care: "Machine wash cold, air dry",
    rating: 4.6,
    reviewCount: 287,
    isBestSeller: true,
  },

  // Women's Clothing - Knitwear
  {
    id: 93,
    name: "Cashmere Sweater",
    price: 159.99,
    category: "Women",
    subcategory: "Clothing",
    type: "Knitwear",
    collection: "Winter 23",
    image: ex75,
    additionalImages: [ex103, ex76],
    inStock: true,
    colors: ["Camel", "Gray", "Dusty Pink"],
    sizes: ["XS", "S", "M"],
    description: "Ultra-soft cashmere crewneck sweater with ribbed trim.",
    details: [
      "Classic crewneck",
      "Ribbed cuffs and hem",
      "Regular fit",
      "Breathable warmth",
      "Luxurious hand feel",
    ],
    materials: "100% Cashmere",
    care: "Hand wash cold, lay flat to dry",
    rating: 4.9,
    reviewCount: 198,
  },
  {
    id: 94,
    name: "Cable Knit Jumper",
    price: 89.99,
    category: "Women",
    subcategory: "Clothing",
    type: "Knitwear",
    collection: "Winter 23",
    image: ex103,
    additionalImages: [ex75, ex77],
    inStock: true,
    colors: ["Cream", "Navy", "Forest Green"],
    sizes: ["S", "M", "L"],
    description: "Chunky cable knit sweater with roll neck and oversized fit.",
    details: [
      "High roll neck",
      "Traditional cable pattern",
      "Oversized silhouette",
      "Ribbed trim",
      "Cozy winter weight",
    ],
    materials: "50% Wool, 50% Acrylic",
    care: "Machine wash cold, lay flat to dry",
    rating: 4.7,
    reviewCount: 156,
  },

  // Women's Clothing - Shirts & Tops
  {
    id: 95,
    name: "Silk Blouse",
    price: 79.99,
    category: "Women",
    subcategory: "Clothing",
    type: "Shirts & Tops",
    collection: "Summer 24",
    image: ex76,
    additionalImages: [ex77, ex78],
    inStock: true,
    colors: ["White", "Black", "Blush Pink"],
    sizes: ["XS", "S", "M"],
    description:
      "Luxury silk blouse with delicate pintucking and French cuffs.",
    details: [
      "Point collar",
      "Hidden button placket",
      "French cuffs",
      "Tailored fit",
      "Tucks at front",
    ],
    materials: "100% Silk charmeuse",
    care: "Dry clean only",
    rating: 4.8,
    reviewCount: 134,
  },
  {
    id: 96,
    name: "Wrap Top",
    price: 49.99,
    category: "Women",
    subcategory: "Clothing",
    type: "Shirts & Tops",
    collection: "Summer 24",
    image: ex77,
    additionalImages: [ex76, ex79],
    inStock: true,
    colors: ["Navy", "Striped", "Solid Black"],
    sizes: ["XS", "S", "M", "L"],
    description:
      "Flattering wrap-style top with self-tie waist and short sleeves.",
    details: [
      "V-neckline",
      "Self-tie closure",
      "Short sleeves",
      "Lightweight fabric",
      "Semi-sheer",
    ],
    materials: "100% Viscose",
    care: "Machine wash cold, hang to dry",
    rating: 4.6,
    reviewCount: 287,
    isBestSeller: true,
  },
  {
    id: 97,
    name: "Button-Up Shirt",
    price: 59.99,
    category: "Women",
    subcategory: "Clothing",
    type: "Shirts & Tops",
    collection: "Summer 24",
    image: ex78,
    additionalImages: [ex76, ex77],
    inStock: true,
    colors: ["White", "Blue Stripe", "Black"],
    sizes: ["XS", "S", "M"],
    description:
      "Classic button-down shirt with tailored fit and spread collar.",
    details: [
      "Spread collar",
      "Chest pocket",
      "Button cuffs",
      "Curved hem",
      "Slightly fitted",
    ],
    materials: "100% Cotton poplin",
    care: "Machine wash warm, iron as needed",
    rating: 4.7,
    reviewCount: 198,
  },
  {
    id: 98,
    name: "Crop Top",
    price: 39.99,
    category: "Women",
    subcategory: "Clothing",
    type: "Shirts & Tops",
    collection: "Summer 24",
    image: ex79,
    additionalImages: [ex77, ex78],
    inStock: true,
    colors: ["White", "Black", "Pastel Yellow"],
    sizes: ["XS", "S", "M"],
    description:
      "Casual ribbed knit crop top with crew neck and short sleeves.",
    details: [
      "Crew neckline",
      "Ribbed knit",
      "Cropped length",
      "Short sleeves",
      "Stretchy fabric",
    ],
    materials: "95% Cotton, 5% Elastane",
    care: "Machine wash cold, lay flat to dry",
    rating: 4.5,
    reviewCount: 176,
    isNew: true,
  },

  // Women's Clothing - Skirts
  {
    id: 99,
    name: "Pencil Skirt",
    price: 69.99,
    category: "Women",
    subcategory: "Clothing",
    type: "Skirts",
    collection: "Summer 24",
    image: ex81,
    additionalImages: [ex82, ex83],
    inStock: true,
    colors: ["Black", "Navy", "Gray"],
    sizes: ["XS", "S", "M"],
    description:
      "Tailored pencil skirt with back slit for professional styling.",
    details: [
      "High waist",
      "Back vent",
      "Hidden back zipper",
      "Knee-length",
      "Lined",
    ],
    materials: "65% Polyester, 30% Viscose, 5% Elastane",
    care: "Dry clean recommended",
    rating: 4.7,
    reviewCount: 143,
  },
  {
    id: 100,
    name: "Pleated Skirt",
    price: 59.99,
    category: "Women",
    subcategory: "Clothing",
    type: "Skirts",
    collection: "Summer 24",
    image: ex82,
    additionalImages: [ex81, ex83],
    inStock: true,
    colors: ["White", "Black", "Pale Blue"],
    sizes: ["XS", "S", "M", "L"],
    description: "Flowy pleated midi skirt with elasticated waist for comfort.",
    details: [
      "Elastic waistband",
      "Accordion pleats",
      "Midi length",
      "Lightweight fabric",
      "No lining",
    ],
    materials: "100% Polyester",
    care: "Machine wash cold, hang to dry",
    rating: 4.6,
    reviewCount: 187,
    isBestSeller: true,
  },
  {
    id: 101,
    name: "Denim Skirt",
    price: 49.99,
    category: "Women",
    subcategory: "Clothing",
    type: "Skirts",
    collection: "Summer 24",
    image: ex83,
    additionalImages: [ex81, ex82],
    inStock: true,
    colors: ["Medium Wash", "Dark Wash", "Black"],
    sizes: ["XS", "S", "M"],
    description: "A-line denim skirt with front button closure and side slits.",
    details: [
      "Button-front",
      "A-line silhouette",
      "Side slits",
      "Five-pocket styling",
      "Mid-thigh length",
    ],
    materials: "98% Cotton, 2% Elastane",
    care: "Machine wash cold, tumble dry low",
    rating: 4.5,
    reviewCount: 156,
  },

  // Women's Clothing - T-Shirts & Sweatshirts
  {
    id: 102,
    name: "Oversized T-Shirt",
    price: 34.99,
    originalPrice: 39.99,
    category: "Women",
    subcategory: "Clothing",
    type: "T-Shirts & Sweatshirts",
    collection: "Summer 24",
    image: ex84,
    additionalImages: [ex85, ex86],
    inStock: true,
    colors: ["White", "Black", "Heather Gray"],
    sizes: ["XS", "S", "M", "L"],
    description:
      "Relaxed oversized cotton tee with dropped shoulders and curved hem.",
    details: [
      "100% cotton jersey",
      "Classic crew neck",
      "Dropped shoulder seams",
      "Slightly curved hem",
      "Unisex fit",
    ],
    materials: "100% Cotton",
    care: "Machine wash cold, tumble dry low",
    rating: 4.7,
    reviewCount: 287,
    isBestSeller: true,
  },
  {
    id: 103,
    name: "Cropped Sweatshirt",
    price: 44.99,
    category: "Women",
    subcategory: "Clothing",
    type: "T-Shirts & Sweatshirts",
    collection: "Winter 23",
    image: ex85,
    additionalImages: [ex84, ex87],
    inStock: true,
    colors: ["Cream", "Pink", "Sage Green"],
    sizes: ["XS", "S", "M"],
    description: "Cozy cropped sweatshirt with ribbed trim and relaxed fit.",
    details: [
      "Fleece-lined interior",
      "Ribbed crew neck",
      "Ribbed cuffs and hem",
      "Cropped length",
      "Kangaroo pocket",
    ],
    materials: "80% Cotton, 20% Polyester",
    care: "Machine wash cold, lay flat to dry",
    rating: 4.6,
    reviewCount: 198,
  },
  {
    id: 104,
    name: "Graphic Tee",
    price: 29.99,
    category: "Women",
    subcategory: "Clothing",
    type: "T-Shirts & Sweatshirts",
    collection: "Summer 24",
    image: ex86,
    additionalImages: [ex84, ex85],
    inStock: true,
    colors: ["White/Black Print", "Black/White Print", "Red/White Print"],
    sizes: ["XS", "S", "M", "L"],
    description:
      "Soft cotton tee with artistic graphic print and feminine fit.",
    details: [
      "Slimmer fit through body",
      "Slightly shorter sleeves",
      "Curved hem",
      "Screen-printed design",
      "Pre-shrunk fabric",
    ],
    materials: "100% Cotton",
    care: "Machine wash cold, inside out",
    rating: 4.5,
    reviewCount: 156,
    isNew: true,
  },
  {
    id: 105,
    name: "Hooded Sweatshirt",
    price: 64.99,
    category: "Women",
    subcategory: "Clothing",
    type: "T-Shirts & Sweatshirts",
    collection: "Winter 23",
    image: ex87,
    additionalImages: [ex85, ex86],
    inStock: true,
    colors: ["Black", "Gray", "Navy"],
    sizes: ["XS", "S", "M", "L"],
    description:
      "Premium heavyweight hoodie with drawstring hood and roomy pocket.",
    details: [
      "Brushed interior",
      "Adjustable drawstring hood",
      "Kangaroo pocket",
      "Ribbed cuffs and hem",
      "Double-lined hood",
    ],
    materials: "85% Cotton, 15% Polyester",
    care: "Machine wash cold, tumble dry low",
    rating: 4.8,
    reviewCount: 234,
  },

  // Women's Clothing - Tailoring Trousers
  {
    id: 106,
    name: "Wide Leg Pants",
    price: 89.99,
    category: "Women",
    subcategory: "Clothing",
    type: "Trousers",
    collection: "Winter 23",
    image: ex88,
    additionalImages: [ex89, ex90],
    inStock: true,
    colors: ["Black", "Camel", "Pinstripe"],
    sizes: ["XS", "S", "M", "L"],
    description:
      "High-waisted wide leg trousers with tailored fit and flowing silhouette.",
    details: [
      "High-rise waist",
      "Wide leg opening",
      "Front pleats",
      "Hidden back elastic",
      "Ankle length",
    ],
    materials: "55% Wool, 45% Polyester",
    care: "Dry clean only",
    rating: 4.7,
    reviewCount: 143,
  },
  {
    id: 107,
    name: "Tailored Trousers",
    price: 99.99,
    category: "Women",
    subcategory: "Clothing",
    type: "Trousers",
    collection: "Winter 23",
    image: ex89,
    additionalImages: [ex88, ex91],
    inStock: true,
    colors: ["Gray", "Navy", "Black"],
    sizes: ["XS", "S", "M"],
    description:
      "Professional straight-leg trousers with crease detail and stretch comfort.",
    details: [
      "Mid-rise waist",
      "Front crease",
      "Hidden zip and button",
      "Functional pockets",
      "Knee-length",
    ],
    materials: "65% Polyester, 30% Viscose, 5% Elastane",
    care: "Machine wash cold, hang to dry",
    rating: 4.8,
    reviewCount: 187,
    isBestSeller: true,
  },

  // Collections - Minimalism and fantasy
  {
    id: 108,
    name: "Minimalist Dress",
    price: 119.99,
    category: "Women",
    subcategory: "Clothing",
    type: "Dresses",
    collection: "Minimalism and fantasy",
    image: ex90,
    additionalImages: [ex91, ex92],
    inStock: true,
    colors: ["Ivory", "Black", "Slate Gray"],
    sizes: ["XS", "S", "M"],
    description:
      "Clean-lined shift dress with architectural seaming and hidden pockets.",
    details: [
      "Round neckline",
      "Cap sleeves",
      "Hidden side pockets",
      "Mid-thigh length",
      "Unlined",
    ],
    materials: "100% Linen",
    care: "Machine wash cold, hang to dry",
    rating: 4.9,
    reviewCount: 98,
  },
  {
    id: 109,
    name: "Abstract Print Top",
    price: 59.99,
    category: "Women",
    subcategory: "Clothing",
    type: "Shirts & Tops",
    collection: "Minimalism and fantasy",
    image: ex91,
    additionalImages: [ex90, ex93],
    inStock: true,
    colors: ["Multicolor", "Black/White", "Blue/Green"],
    sizes: ["XS", "S", "M"],
    description:
      "Art-inspired abstract print blouse with dramatic sleeves and tie neck.",
    details: [
      "Signature artist print",
      "Bell sleeves",
      "Self-tie neck",
      "Semi-sheer",
      "Loose fit",
    ],
    materials: "100% Silk",
    care: "Dry clean only",
    rating: 4.7,
    reviewCount: 134,
  },
  {
    id: 110,
    name: "Geometric Earrings",
    price: 39.99,
    category: "Women",
    subcategory: "Accessories",
    type: "Jewelry",
    collection: "Minimalism and fantasy",
    image: ex92,
    additionalImages: [ex90, ex91],
    inStock: true,
    colors: ["Gold", "Silver", "Rose Gold"],
    description:
      "Modern geometric drop earrings with minimalist angular design.",
    details: [
      '1.5" drop length',
      "Surgical steel posts",
      "Lightweight construction",
      "Hypoallergenic",
      "Gift box included",
    ],
    materials: "Brass with gold/silver plating",
    care: "Store in jewelry box to prevent tarnishing",
    rating: 4.8,
    reviewCount: 187,
    isNew: true,
  },
  {
    id: 111,
    name: "Autumn Blazer",
    price: 149.99,
    category: "Women",
    subcategory: "Clothing",
    type: "Jackets & Coats",
    collection: "Pre Fall 23",
    image: ex93,
    additionalImages: [ex90, ex92],
    inStock: true,
    colors: ["Camel", "Olive Green", "Rust"],
    sizes: ["XS", "S", "M"],
    description:
      "Unstructured blazer with notched lapels and seasonal earth-tone colors.",
    details: [
      "Unlined construction",
      "Patch pockets",
      "Single-button closure",
      "Slightly cropped",
      "Rolled sleeves",
    ],
    materials: "55% Linen, 45% Cotton",
    care: "Dry clean recommended",
    rating: 4.7,
    reviewCount: 112,
  },

  // Women's Suits
  {
    id: 112,
    name: "Women's Tailored Suit",
    price: 299.99,
    category: "Women",
    subcategory: "Clothing",
    type: "Suits",
    collection: "Winter 23",
    image: ex104,
    additionalImages: [ex105, ex90],
    inStock: true,
    colors: ["Navy", "Black", "Gray"],
    sizes: ["XS", "S", "M", "L"],
    description:
      "Professional two-piece suit with sculpted blazer and straight-leg trousers.",
    details: [
      "Notched lapel blazer",
      "Single-breasted",
      "Functional buttons",
      "Straight-leg trousers",
      "Fully lined",
    ],
    materials: "70% Wool, 28% Polyester, 2% Elastane",
    care: "Dry clean only",
    rating: 4.9,
    reviewCount: 87,
    isBestSeller: true,
  },
  {
    id: 113,
    name: "Women's Pantsuit",
    price: 279.99,
    category: "Women",
    subcategory: "Clothing",
    type: "Suits",
    collection: "Winter 23",
    image: ex105,
    additionalImages: [ex104, ex93],
    inStock: true,
    colors: ["Black", "Charcoal", "Pinstripe"],
    sizes: ["XS", "S", "M"],
    description:
      "Modern pantsuit with cropped blazer and wide-leg trousers for power dressing.",
    details: [
      "Cropped single-button blazer",
      "Wide-leg trousers",
      "High-rise waist",
      "Functional pockets",
      "Lined throughout",
    ],
    materials: "65% Wool, 30% Polyester, 5% Elastane",
    care: "Professional dry clean only",
    rating: 4.8,
    reviewCount: 76,
  },
];

// Filter functions for all categories
export const menProducts = allProducts.filter(
  (product) => product.category === "Men"
);
export const womenProducts = allProducts.filter(
  (product) => product.category === "Women"
);

// Men's subcategories
export const menAccessories = menProducts.filter(
  (product) => product.subcategory === "Accessories"
);
export const menBelts = menAccessories.filter(
  (product) => product.type === "Belts"
);
export const menGiftsForHim = menAccessories.filter(
  (product) => product.type === "Gifts for him"
);
export const menJewelry = menAccessories.filter(
  (product) => product.type === "Jewelry"
);
export const menPocketSquares = menAccessories.filter(
  (product) => product.type === "Pocket Squares"
);
export const menTies = menAccessories.filter(
  (product) => product.type === "Ties"
);
export const menBowTies = menAccessories.filter(
  (product) => product.type === "Bow Ties"
);

export const menClothing = menProducts.filter(
  (product) => product.subcategory === "Clothing"
);
export const menSuits = menClothing.filter(
  (product) => product.type === "Suits"
);
export const menJeans = menClothing.filter(
  (product) => product.type === "Jeans"
);
export const menPants = menClothing.filter(
  (product) => product.type === "Pants"
);
export const menPolos = menClothing.filter(
  (product) => product.type === "Polos"
);
export const menShirts = menClothing.filter(
  (product) => product.type === "Shirts"
);
export const menSweatshirts = menClothing.filter(
  (product) => product.type === "Sweatshirts & Hoodies"
);
export const menTShirts = menClothing.filter(
  (product) => product.type === "T-Shirts"
);
export const menTuxedos = menClothing.filter(
  (product) => product.type === "Tuxedos"
);
export const menWaistcoats = menClothing.filter(
  (product) => product.type === "Waistcoats"
);

// Women's subcategories
export const womenAccessories = womenProducts.filter(
  (product) => product.subcategory === "Accessories"
);
export const womenEyewear = womenAccessories.filter(
  (product) => product.type === "Eyewear"
);
export const womenGifts = womenAccessories.filter(
  (product) => product.type === "Gifts for her"
);
export const womenHats = womenAccessories.filter(
  (product) => product.type === "Hats & Scarves"
);
export const womenHosiery = womenAccessories.filter(
  (product) => product.type === "Hosiery"
);
export const womenJewellery = womenAccessories.filter(
  (product) => product.type === "Jewelry"
);

export const womenClothing = womenProducts.filter(
  (product) => product.subcategory === "Clothing"
);
export const womenSuits = womenClothing.filter(
  (product) => product.type === "Suits"
);
export const womenDresses = womenClothing.filter(
  (product) => product.type === "Dresses"
);
export const womenDenim = womenClothing.filter(
  (product) => product.type === "Denim"
);
export const womenGowns = womenClothing.filter(
  (product) => product.type === "Gowns"
);
export const womenJackets = womenClothing.filter(
  (product) => product.type === "Jackets & Coats"
);
export const womenKnitwear = womenClothing.filter(
  (product) => product.type === "Knitwear"
);
export const womenShirts = womenClothing.filter(
  (product) => product.type === "Shirts & Tops"
);
export const womenSkirts = womenClothing.filter(
  (product) => product.type === "Skirts"
);
export const womenSweatshirts = womenClothing.filter(
  (product) => product.type === "T-Shirts & Sweatshirts"
);
export const womenTailoring = womenClothing.filter(
  (product) => product.type === "Tailoring"
);
export const womenTrousers = womenClothing.filter(
  (product) => product.type === "Trousers"
);

// Collections
export const minimalismFantasy = allProducts.filter(
  (product) => product.collection === "Minimalism and fantasy"
);
export const preFall23 = allProducts.filter(
  (product) => product.collection === "Pre Fall 23"
);
export const preSpring23 = allProducts.filter(
  (product) => product.collection === "preSpring23"
);
export const preSpring24 = allProducts.filter(
  (product) => product.collection === "Pre-Spring 24"
);
export const readyToWear = allProducts.filter(
  (product) => product.collection === "Ready to wear"
);
export const summer23 = allProducts.filter(
  (product) => product.collection === "Summer 23"
);
export const summer24 = allProducts.filter(
  (product) => product.collection === "Summer 24"
);
export const winter22 = allProducts.filter(
  (product) => product.collection === "Winter 22"
);
export const winter23 = allProducts.filter(
  (product) => product.collection === "Winter 23"
);
export const winter24 = allProducts.filter(
  (product) => product.collection === "Winter 24"
);
